export enum NotificationType {
  LOGIN = 'login',
  LOGOUT = 'logout',
  REGISTRATION = 'registration',
  SEND_MONEY = 'send_money',
  RECEIVE_MONEY = 'receive_money',
  SWAP = 'swap',
  DEPOSIT = 'deposit',
  WITHDRAWAL = 'withdrawal',
  OTP_VERIFIED = 'otp_verified',
  PASSWORD_CHANGE = 'password_change',
  SECURITY_ALERT = 'security_alert',
  CONVERSION_STARTED = 'conversion_started',
  CONVERSION_COMPLETED = 'conversion_completed',
  CONVERSION_FAILED = 'conversion_failed',
  CONVERSION_CANCELLED = 'conversion_cancelled',
  QR_PAYMENT_CREATED = 'qr_payment_created',
  QR_PAYMENT_RECEIVED = 'qr_payment_received',
  AIRTIME_PURCHASE = 'airtime_purchase',
  DATA_PURCHASE = 'data_purchase',
  UTILITY_PAYMENT = 'utility_payment',
  PURCHASE_FAILED = 'purchase_failed',
  SEND = 'Payment sent',
  DEPLOY = 'DEPLOY',
  QR_PAYMENT_COMPLETED = 'QR_PAYMENT_COMPLETED',
  CANCELLED = 'CANCELLED',
}

export default NotificationType;
